### ISSUE TITLE
RIS file format is documented to be encoded in windows-1252 but is generated as UTF-8

### ISSUE THREAD

**Issue by uschindler** [datacite/content-resolver#1]
The RIS file format is oficially documented to be (for historic reasons, unfortunately) in the windows-1252 character set. The content-resolver returns the text data in UTF-8. This makes it ususeable for citations with umlauts, if you try to import them into Endnote. The same issue exists for Crossref output.

For PANGAEA (where we use the crossref and datacite content negotiation to get full citation information), we use Apache Tika's caracter sets auto-negotiation before parsing the RIS file, but thats not agood idea.

I just opened the issue to hopefully fix this (in communication with Crossref).

**Comment by mfenner** [comment]
It took me a while. The fix be deployed later today. Also made a third change to the RIS output: one line per author : #29.
