### ISSUE TITLE
BIBTEX output format does not escape characters according to Latex

### ISSUE THREAD

**Issue by uschindler** [datacite/content-resolver#2]
The Latex escapes a lot of common characters, so importing the BIBTEX files from content-resolver in most cases lead to Latex errors. The rules for escaping characters are very complicated.

At PANGAEA we have an escaper class for BIBTEX that handles most of western chars to be correctly escaped when exported as Latex text (used by BIBTEX). We can provide this Java code here, it should be available to everyone. Its mainly a POJO with a static method that gets a String and returns the String as escaped Latex code.

**Comment by mfenner** [comment]
Is the Pangaea code still useful, or does the Pangaea implementation look very different now?

**Comment by uschindler** [comment]
No changes here!

**Comment by mfenner** [comment]
Thanks! Added latex escaping to bibtex output. Also added an abstract field.

As citation key I prefer to use the the DOI expressed as URL. Better than the UUID that changes on every request.

**Comment by uschindler** [comment]
Thanks. When reviewing our changes I found a small change added later:
- The above code misses to encode the degree sign correctly
- It does not encode any other special chars and replaces them by "?"

The fix is here:

```diff
Index: XSLTFunctions.java
===================================================================
--- XSLTFunctions.java	(revision 4295)
+++ XSLTFunctions.java	(revision 4296)
@@ -5,6 +5,7 @@
 import java.io.StringReader;
 import java.io.StringWriter;
 import java.net.URL;
+import java.util.Locale;
 import java.util.regex.Pattern;
 
 import javax.xml.parsers.DocumentBuilderFactory;
@@ -123,7 +124,8 @@
 								
 				case '\u00DF': sb.append("{\\ss}"); break;
 				case '\u00A0': sb.append('~'); break; // &nbsp;
-				case '\u00BA': sb.append("{\\textdegree}"); break;
+				case '\u00BA': 
+				case '\u00B0': sb.append("{\\textdegree}"); break;
 				case '"': sb.append("{\"}"); break;
 				
 				case 13:
@@ -146,11 +148,14 @@
 				case '{':
 				case '}':
 				case '_':
-					sb.append('\\');
-					sb.append(ch);
+					sb.append('\\').append(ch);
 					break;
 				default:
-					sb.append( (ch<0x80)?ch:'?' );
+				  if (ch<0x80) {
+				    sb.append(ch);
+				  } else {
+				    sb.append(String.format(Locale.ROOT, "{\\char\"%04X}", Integer.valueOf(ch)));
+				  }
 			}
 		}
 		return sb.toString();
```

**Comment by uschindler** [comment]
I am not sure if Bibtex allows to use an URI as identifier for citations. Our code creates a typical bibtex styled reference identifier using the author name and the year, e.g., "maturilli2016baom" for this one:

```
@misc{maturilli2016baom,
 author={Marion {Maturilli} and Christoph {Ritter}},
 title={{Basic and other measurements of radiation at station Ny-{\char"00C5}lesund (2015-03)}},
 year={2016},
 doi={10.1594/PANGAEA.854326},
 url={https://doi.pangaea.de/10.1594/PANGAEA.854326},
 note={Supplement to: Maturilli, Marion; Ritter, Christoph (2016): Surface radiation during the total solar eclipse over Ny-{\char"00C5}lesund, Svalbard, on 20 March 2015. Earth System Science Data, 8(1), 159-164, doi:10.5194/essd-8-159-2016},
 abstract={On 20 March 2015, a total solar eclipse occurred over Ny-{\char"00C5}lesund (78.9{\char"00B0} N, 11.9{\char"00B0} E), Svalbard, in the high Arctic. It was the first time that the surface radiation components during the totality of a solar eclipse were measured by a Baseline Surface Radiation Network (BSRN) station. With the Ny-{\char"00C5}lesund long-term radiation data set as background (available at doi:10.1594/PANGAEA.150000), we present here the peculiarities of the radiation components and basic meteorology observed during the eclipse event. The supplementary data set contains the basic BSRN radiation and surface meteorological data in 1 min resolution for March 2015, and is available at doi:10.1594/PANGAEA.854326. The eclipse radiation data will be a useful auxiliary data set for further studies on micrometeorological surface-atmosphere exchange processes in the Svalbard environment, and may serve as a test case for radiative transfer studies.},
 type={data set},
 publisher={PANGAEA}
}
```

**Comment by mfenner** [comment]
OK, will look into URI as bibtex key. I have used them for a while now in internal projects, e.g. for the DataCite blog (where in-text citations generated by Pandoc are made actionable using the key).

**Comment by uschindler** [comment]
No problem, I was just not sure if it works with Bibtex/Latex at all. I was under the assumption that it only allows "identifier-like" stuff. Our keys are just formed according to the "convention" in Latex world:
- Last name of first author in lowercase
- Year
- first char extracted from first 4 words of title

I have no reference where this is defined it is just the way how publishers and software tools produce their files! :-)
