### ISSUE TITLE
Why are DOIs converted to uppercase?

### ISSUE THREAD

**Issue by dhimmel** [datacite/content-resolver#23]
I see that many DataCite services seem to provide DOIs in ALL CAPS. For example, `10.5281/ZENODO.48810` rather than `10.5281/zenodo.48810`. I didn't know until now that DOI resolution was case agnostic.

However, I view it as extremely undesirable to transform DOIs from their registered case. Basically, this defies the uniqueness tenant of the DOI system. In other words, I can no longer use DOIs as a primary key for a resource without converting to lowercase myself?

**Comment by dhimmel** [comment]
Here's what the [DOI guidelines](https://www.doi.org/doi_handbook/2_Numbering.html#2.4) say about case sensitivity:

> DOI names are case insensitive, using ASCII case folding for comparison of text. (Case insensitivity for DOI names applies only to ASCII characters. DOI names which differ in the case of non-ASCII Unicode characters may be different identifiers.) 10.123/ABC is identical to 10.123/AbC. All DOI names are converted to upper case upon registration, which is a common practice for making any kind of service case insensitive. The same is true with resolution. If a DOI name were registered as 10.123/ABC, then 10.123/abc will resolve it and an attempt to register 10.123/AbC would be rejected with the error message that this DOI name already existed.

> Although from a character encoding viewpoint suffixes are case sensitive, e.g. 10.123/ABC is different from 10.123/AbC and the two could be distinguished as different identifiers, the IDF decided to remove case sensitivity, after a detailed review of the consequences. The Handle System is configurable by service so as to be either case sensitive or case insensitive and therefore allows this. This restriction has been implemented from an early stage, and IDF agencies have not introduced any cases of two DOI names distinguishable only by ASCII case resolving to the same thing.

> The advantages of case sensitivity (librarian and publisher practice, human readability and expectations) were outweighed by considerations of data integrity. Case sensitivity practice across Internet applications varies: DNS is not, the rest of URLs are except sometimes they aren't (this depends on the server), Unix vs PC/Mac file names (Microsoft Windows in general is not case-sensitive, Unix operating systems are always case sensitive), markup language tags, etc. can all cause unexpected problems and one cannot guarantee that any particular piece of software will respect case sensitivity and not conflate two DOI names intended to be different. Some search engines and directories are partially case sensitive. Different web browsers may differ in case sensitive handling (web browser developers have advised that "authors should not rely on case-sensitivity as a way of creating distinct identifiers, unless they are designing solely for a truly standards-compliant browser").

> This argued in favour of case insensitivity being the safer, and more robust, option for future evolution and development of the DOI system.

Give me a bit of time to consider whether deviating from the registered casing should be discouraged. If not, I'll close this issue.

**Comment by mfenner** [comment]
Agree that a consistent pattern to always use DOI names in either uppercase or lowercase is helpful. Discussing this with Crossref right now, and also considering the DOI guidelines from the IDF. 

For the time being we will encounter DOIs in both uppercase and lowercase and have to transform them internally in a consistent way if used as key.

Closing this issue for now.
