### ISSUE TITLE
RDF misses several metadata attributes

### ISSUE THREAD

**Issue by hlapp** [datacite/content-resolver#9]
The turtle and RDF/XML representations seem to be missing several of the metadata attributes, including some which would seem important for machine aggregation, such as rights, citation, isPartOf, and subjects.

Example is here:
http://data.datacite.org/10.5061/DRYAD.17VS2D34/1

It'd be great if this can be fixed.

**Comment by mfenner** [comment]
Implemented in crosscite/content-negotiation. Which is behind data.datacite.org since 16 May 2017.
